stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - npm install --force
    - npm run build

trigger-deploy:
  stage: deploy
  trigger: digitalmemory/openshift-deploy
