stages:
  - build
  - deploy

build:
  stage: build
  image: node:18
  script:
    - npm install --force
    # Set CI to false otherwise craco treats eslint warnings as errors..
    - CI=false npm run build

trigger-deploy:
  stage: deploy
  trigger: digitalmemory/openshift-deploy
